# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecompilerbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='codename',
        ),
        migrations.AddField(
            model_name='language',
            name='value',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
