# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecompilerbot', '0002_auto_20170524_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='shortname',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
