# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecompilerbot', '0003_language_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='shortname',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='language',
            name='value',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
