# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecompilerbot', '0004_auto_20170524_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='default_code',
            field=models.TextField(blank=True),
        ),
    ]
